AllCops:
  Exclude:
    - vendor/**/*
    - public/**/*
    - spec/javascripts/**/*
    - tasks/**/*
    - Guardfile

Layout/IndentationWidth:
  Width: 4

Style/SymbolArray:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Naming/VariableName:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Max: 300

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 200

Layout/BlockAlignment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/DateTime:
  Enabled: false

inherit_from: .rubocop_todo.yml
