language: ruby

sudo: true

rvm:
  - "2.2.5"

before_install:
  - sudo apt-get install libmagic-dev
  - gem update --system
  - gem --version
  - gem install rspec

before_script:
  - cp config/database.rb.sample config/database.rb
  - cp config/options.rb.sample config/options.rb
  - mysql -e 'create database CahierDeTextes;'
  - bundle install
  - bundle exec rake db:migrate

script:
  - "bundle exec rspec ./spec/api ./spec/models ./spec/lib"
  - "bundle exec rubocop -D"
#  - "bundle exec reek --sort-by smelliness *.rb api lib migrations models routes views tasks spec"
  - "bundle exec rake preprocess_assets:production"

gemfile:
  - Gemfile

services:
  - mysql

branches:
  only:
    # - master
    - develop

notifications:
  email:
    recepients:
      - glemoine@erasme.org
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
