language: ruby

sudo: true

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p
  - sudo service mysql restart
  - export TZ=Europe/Paris

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/options.rb.sample config/options.rb
  - mysql -e 'create database CahierDeTextes;'
  - bundle install
  - make db-migrate

script:
  - "bundle exec rspec"
  - "bundle exec rubocop -D"

services:
  - mysql

branches:
  only:
    - develop

notifications:
  email:
    recepients:
      - glemoine@erasme.org
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
