language: ruby
rvm:
  - "2.1.3"

before_install:
  - gem update --system
  - gem --version
  - gem install rspec

before_script:
  - for sample in config/*.sample; do cp $i ${i%.sample}; done
  - mysql -e 'create database CahierDeTextes;'
  - bundle exec rake db:migrations

script: "bundle exec rspec spec/api/ spec/lib/"

gemfile:
  - Gemfile

services:
  - mysql

branches:
  only:
    # - master
    - develop

notifications:
  email:
    recepients:
      - glemoine@erasme.org
  # slack:
  #   rooms:
  #     - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
