language: ruby

sudo: false

rvm:
  - "2.5.1"

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/options.rb.sample config/options.rb
  - mysql -e 'create database CahierDeTextes;'
  - bundle install
  - make db-migrate

script:
  - "bundle exec rspec ./spec/api ./spec/models ./spec/lib"
  - "bundle exec rubocop -D"

services:
  - mysql

branches:
  only:
    - develop

notifications:
  email:
    recepients:
      - glemoine@erasme.org
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
