language: ruby
rvm:
  - "2.2.0"

before_install:
  - gem update --system
  - gem --version
  - gem install rspec

before_script:
  - cp config/constants.rb.sample config/constants.rb
  - cp config/database.rb.sample config/database.rb
  - cp config/options.rb.sample config/options.rb
  - cp config/thin.yml.sample config/thin.yml
  - mysql -e 'create database CahierDeTextes;'
  - bundle exec rake db:migrations

script:
  - "bundle exec rspec"
  - "bundle exec rubocop -D"

gemfile:
  - Gemfile

services:
  - mysql

branches:
  only:
    # - master
    - develop

notifications:
  email:
    recepients:
      - glemoine@erasme.org
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
