# -*- coding: utf-8; mode: ruby -*-

source 'https://rubygems.org'
# source 'http://gems.erasme.org'

gem 'grape'
gem 'grape-swagger'
gem 'mysql2'
gem 'nokogiri'
gem 'omniauth-cas'
gem 'rack'
gem 'rack-rewrite'
gem 'rake'
gem 'rest-client'
gem 'sequel'
gem 'sinatra'
gem 'puma'
gem 'rubyzip'
gem 'uglifier'
gem 'sass'

gem 'laclasse-common', git: 'https://github.com/laclasse-com/laclasse-common.git', tag: '0.2.2'

group :development do
  # gem 'guard'
  # gem 'guard-rake'
  # gem 'guard-rspec'
  # gem 'guard-bundler'
  # gem 'guard-shell'
  gem 'jasmine'
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
  # gem 'simplecov'
  gem 'selenium-webdriver'
  gem 'capybara'
  gem 'show_me_the_cookies'
  gem 'rubocop'
  gem 'rubocop-rspec'
end
