user: erasme
group: erasme
pid: /var/run/service-cahiertextes/thin.pid
log: /var/log/service-cahiertextes/thin.log
timeout: 30
max_conns: 1024
port: 9292
max_persistent_conns: 512
environment: production
adapter: rack
servers: 2 
daemonize: true
tag: service-cahiertextes
